<?php

/**
 * This file is part of the authbucket/oauth2-php package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace SimpleUser\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomFieldsRepository extends EntityRepository
{
	protected $class = "\\SimpleUser\\Entity\\CustomFields";
    public function getTableName() {
        return $this->getEntityManager()->getClassMetadata($this->class)->getTableName();
    }
}

